name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./package.json

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Set up Postgres
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: postgres
          password: password
          database: postgres

      - name: Build UI
        working-directory: ui
        run: |
          pnpm build

