name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build UI
        working-directory: ui
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Test server
        working-directory: server
        run: |
          pnpm install --frozen-lockfile
          pnpm test:ci

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Postgres
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: postgres
          password: password
          database: postgres

      - name: Run server tests with coverage
        env:
          NODE_ENV: test
          FIREBASE_PROJECT_ID: demo-project
          DATABASE_URL_TEST: postgresql://postgres:password@localhost:5432/postgres
        run: |
          cd server
          pnpm run test:ci


