name: Web Deploy (dev)

on:
  push:
    branches: [ "main" ]
    paths:
      - "ui/**"
      - ".github/workflows/web-deploy.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: web-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        env:
          VITE_USE_API: "1"
          VITE_API_URL: ${{ secrets.API_BASE_URL }}
        run: pnpm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Required: set this repo secret from your SWA "Deployment token"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Optional: enables PR comments, etc.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          # We’re uploading the prebuilt artifacts
          app_location: ui/dist
          output_location: ""
          skip_app_build: true
