name: Web Deploy (dev)

on:
  push:
    branches: [ "main" ]
    paths:
      - "ui/**"
      - ".github/workflows/web-deploy.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('ui/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps
        run: |
          cd ui
          pnpm fetch
          pnpm install --no-frozen-lockfile --prefer-offline

      - name: Build web
        env:
          VITE_USE_API: "1"
          VITE_API_URL: ${{ secrets.API_BASE_URL }}
        run: |
          cd ui
          pnpm run build

      # Deploy prebuilt files; skip Oryx build entirely
      - name: Deploy to Azure Static Web Appss
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_app_build: true
          skip_api_build: true
          app_location: ui/dist
          output_location: ''
          required when skip_app_build: true
